version: '3.8'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ptcgproot
    ports:
      - "2517:2716"
  web:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    depends_on:
      - mongo
